### ISSUE TITLE
Teamselectie controleert niet de voorwaarden

### ISSUE THREAD

**Issue by Bierfietsen** [RensReus/Sportradenenzo#25]
Voorwaarden waar aan voldaan moet worden:
Voldoende budget
Max. 4 renners per team

**Comment by RensReus** [comment]
De (sql) code staat al grotendeels ergens in de oude versie
ik zal het implementeren voor de giro

**Comment by Bierfietsen** [comment]
Dit moet ook nog gebeuren aan de front-end
