### ISSUE TITLE
Minderen kwa connecties met sql

### ISSUE THREAD

**Issue by RensReus** [RensReus/Sportradenenzo#33]
Er zijn er nu veel te veel waardoor we heel vaak op 20/20 zitten wat de website onbruikbaar maakt.
Het komt wss door iets met de nieuwe opzet.
Sowieso moeten we ff opnieuw kijken naar hoe we omgaan met de db dmv queries enzo.

**Comment by Bierfietsen** [comment]
Connecties per sessie teruggebracht naar 1
