### ISSUE TITLE
token expired handling

### ISSUE THREAD

**Issue by RensReus** [RensReus/Sportradenenzo#52]

**Comment by Bierfietsen** [comment]
TODOS:
- Token moet 5 weken houdbaar zijn (bij voorkeur gebruik maken van refresh tokens die na elk sitebezoek de token verversen)
- Als token expired is moet er goede logout handling komen die de gebruiker opnieuw laat inloggen

**Comment by RensReus** [comment]
tokens zijn langer houdbaar en indien verlopen redirect naar login
