### ISSUE TITLE
TODOs voor de tour

### ISSUE THREAD

**Issue by RensReus** [RensReus/Sportradenenzo#78]
Als meer deelnemers:
kijken hoe bepaalde statistieken en graphs er uit zien. En dan wss beslissen om die uit te zetten/ verbergen voor de andere mensen
hier voor moeten we poules aan de db gaan toevoegen
budget spel ook uitzetten voor ze

**Comment by RensReus** [comment]
Bij de selectie pagina sorteren op skills/ weergeven van deze extra info
we hebben dit nu beschikbaar via de scorito import dus er is daar best wat mogelijk
extension op db en importeren zal niet heel lastig zijn wss
maar aangepaste design voor teamselection page wss wel

**Comment by RensReus** [comment]
Redesign teamselection

**Comment by Bierfietsen** [comment]
Site bruikbaar maken op telefoon, hoeft niet heel mooi te zijn maar wel zorgen dat alles werkt

**Comment by RensReus** [comment]
(klassementen) tabel met vaste kolom groottes
Dan moeten we ook iets doen met te lange strings 
Cutoff met...

**Comment by RensReus** [comment]
hide statistieken(behalve uitslagen per ronde) en charts als er geen huidige race is geselecteerd

**Comment by RensReus** [comment]
hide login page while waiting for BE call

**Comment by Bierfietsen** [comment]
Duidelijke uitleg regels en punten maken. Knop hiervoor plaatsen op teamselectie pagina en stage pagina

**Comment by RensReus** [comment]
alles verplaatst naar milestone
